require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'


target 'blue_baley' do
  config = use_native_modules!
  # Pods for blue_baley
  pod 'Stripe', '~> 14.0.0'

  use_react_native!(:path => config["reactNativePath"])

  target 'blue_baleyTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'blue_baley-tvOS' do
  # Pods for blue_baley-tvOS

  target 'blue_baley-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
